# Generated by Django 3.1.7 on 2021-05-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=70)),
                ('card', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_word', models.CharField(max_length=50)),
                ('card_definition', models.CharField(max_length=100)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.collection')),
            ],
        ),
    ]
