# Generated by Django 3.1.7 on 2021-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20210503_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='card_definition',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='card_word',
            field=models.CharField(max_length=120),
        ),
    ]
