# Generated by Django 3.1.7 on 2021-05-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_auto_20210505_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='card_definition',
            new_name='card_answer',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='card_word',
            new_name='card_question',
        ),
    ]
